// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nursgmgvvgpzxekxfhtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51cnNnbWd2dmdwenhla3hmaHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTgzMTMsImV4cCI6MjA3MDk5NDMxM30.N0kMTvKZ8N8LEM2oRwLDbLrO31C3BQ6Ymoa5_sEOqSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});